version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.4.0
    - 5.5.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: broccoli
    versions:
    - 3.5.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 8.14.0
